language: cpp
compiler:
  - clang
  - gcc
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libeigen3-dev
 - git clone https://github.com/PetterS/spii.git spii
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.7; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
 - $CXX --version
before_script:
  - mkdir build
  - cd build
  - cmake -DOPENMP=OFF -DSPII_INCLUDE=../spii/include .. 
script: 
  - make && ctest --output-on-failure
notifications:
  email:
    - ulen@maths.lth.se
    - petter.strandmark@gmail.com
